name: Dat site title tho
author: Halan Pinheiro
description: 
url: "http://yourdomain.com"

locale: 'pt-BR'

exclude: [ Gemfile, Gemfile.lock]
markdown: redcarpet
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed

